import 'package:flutter/cupertino.dart';
import 'package:shared_preferences/shared_preferences.dart';

class Language with ChangeNotifier {
  // language dir
  String languageDirection;

  // language code
  String languageCode;

  void setLanguage(code, direction) async {
    languageCode = code;
    languageDirection = direction;
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    sharedPreferences.setString('languageCode', languageCode);
    sharedPreferences.setString('languageDirection', direction);
    notifyListeners();
  }

  Future<void> getLanguageDataInLocal() async {
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    languageCode = sharedPreferences.getString('languageCode') ?? 'en';
    languageDirection =
        sharedPreferences.getString('languageDirection') ?? 'ltr';
    notifyListeners();
  }

  Map<String, dynamic> get words => _words[languageCode];

  // language words
  Map _words = {
    'kr': {
      //login
      'login': "چوونەژورەوە",
      'logout': "دەرچوون",
      'sale-person': "فرشیار",
      'shop': "دوکان",
      'nawras': "نەورەس",
      'welcome': "بەخربیێیت",
      'phone number': "ژمارەی مۆبایل",
      'password': "وشەی نهێنی",
      'forget something': "شتەکت بییرچۆتەوە؟!",
      'sure-log-out': "ئایا دڵنیایت لەوەی کە دەچیتە دەرەوە؟",
      'log-out': " چوونە دەرەوە",
      "forget-password-warning":
          "ئایا هیچ کێشەیت هەیە لەکاتی چوونە ژوورەوە؟! n بۆ بەدەستهێنانی و ڕیسێتکردنی نهێنوشە تەنها پەیوەندی بکە بە کۆمپانیاکەمان... ",
      "password-short": "نهێنوشەکەت زۆر کورتەً..",
      "number-not-valid": "ژمارەی تەلەفۆن دەبێت 7 یان زیاتر بێت..",

      //home screen
      "home": "ماڵەوە",
      "activity": "چالاکی",
      "requests": "داواکاریەکان",
      "request": "داواکاری",
      "favorites": "دڵخوازەکان",
      "offers": " ئۆفەرەکان",
      "categories": "هاوپۆلەکان",
      "details-product": " ووردەکاری بەرهەم",
      "search": "گەڕان",
      "search-hint": "گەڕان بۆ شتێک",
      "all": "هەموو",
      "most-popular": "بەناوبانگترین",
      "best-seller": "باشترین فرۆشیار",
      "new-product": "بەرهەمی نوێ",
      "settings": "ڕێکخستنەکان",
      "profile": "پرۆفایل",
      "view-profile": "پرۆفایل نیشان بدە",
      "feedback": "کاردانەوە",
      "language": "زمان",
      "display-mode": "دۆخی پیشاندان",
      "contact": " پەیوەندی",
      "contact-us": " پەیوەندی",
      "about": " ده رباره",
      "schedule": "خشتەی کار",
      "notifications": " ئاگانامەکان",
      "cart": "سەبەتە",
      "order-count": "ژمارەی داواکراوەکان",
      "change-language": "گۆڕینی زمان",
      "total-price": "کۆی نرخ",
      "total-products": "کۆی بەرهەمەکان",
      "search-for-product": "گەڕان بۆ بەرهەمەکان ...",
      "type-here": "لێرە بنووسە ...",
      "exit": "انهاء",
      "sure-exit": "ئایا دڵنیایت لە بەرجەستەکراوی دەرچوون؟",
      "select-market": "مارکێتێک دیاریبکە",
      "update": "نوێکردنەوە",

      //details product screen
      "add-to-card": "زیادکردن بۆ کارت",
      "product-already-order": "ئەم بەرهەمە پێشتر داوای کردووە!",
      "add-to-your-a-cart": "زیادکردن بۆ عەرەبانەکەت",
      "expire-date": "بەرواری بەسەرچوو",
      "price": "نرخ",
      "weight": "کێش",
      "package-weight": "کێشی گورزە",

      // Cart order
      'the-order-was-successful': 'داواکردنەکە سەرکەوتوو بوو',
      "buying-these-products": "دڵنیایت کە ئەم بەرهەمانە دەکڕیت",

      //Profile Screen
      "full-name": " ناوی تەواو",
      "number-phone": " ژمارەی تەلەفۆن",
      "user-type": "جۆری بەکارهێنەر",
      "location": "شوێن",
      "zone": "ناوچە",
      "market": "بازاڕ",
      "phone": "تەلەفۆن",
      "area": "بەش",
      "date": "بەروار",
      "items": "بەرهەم",
      "item": "بەرهەم",

      //Feedback Screen
      "feedback-title": "کاردانەوەکەتمان بۆ بنێرە",
      "feedback-desc":
          "ئایا پێشنیارێکت هەیە یان هەندێک دیبی دۆزیەوە؟\n لە فیلدی خوارەوە پێمان بڵێ.",
      "title": "ناونیشان",
      "name": "ناو",
      "valid-name": "ناوی دروست بنووسێ تکایە ...",
      "valid-title": "ناونیشانی دروست بنوسێت تکایە ...",
      "valid-message": "تکایە نامەی دروست بنووسێت ...",
      "title-desc": "چۆن وەک ئەزموونەکەت",
      "desc-desc": "لێرەدا باسی ئەزموونەکەت بکە",

      //Marketing Screen
      "marketing-form": "فۆرمی بازاڕکردن",
      "fill-out-feedback": "پڕکردنەوەی فۆرمی فیدباکی خوارەوە",
      "market-info": "زانیاری بازار",
      "old-new": "کۆن یان نوێ",
      "do-have": "ئایا بەرهەمی نەورەست هەیە",
      "if-do": "ئەگەر بەرهەمی نەوڕەس بەکار نەهینین، با بزانین بۆچی؟",
      "barprsy-mushtaryat": "بەرپرسی موشتەریات ",
      "barprs": "بەرپرس",
      "expo": "ڕوونکردنەوە",
      "bronze": "برۆنز",
      "silver": "زیو",
      "gold": "زێڕ",
      "platinum": "پلاتین",
      "name-of-market": "ناوی بازار:",
      "owner-name": "ناوی خاوەن:",
      "address": "ناونیشان:",
      "near": "نزیک:",
      "old": "کۆن",
      "new": "نوێ",
      "yes": "بەڵێ",
      "no": "نەخێر",
      "type": "جۆر",
      "plural": "کۆ",
      "singular": "تاک",
      "volume": "قەبارە",
      "small": "بچووک",
      "medium": "ناوەند",
      "large": "گەورە",
      "mini-market": "مینی مارکێت ",
      "super-market": "سوپەر مارکێت",
      "hyper-market": "هایپەر مارکێت",
      "image": "وێنە",
      "note": "تێبینی",
      "add-note": "زیادکردنی تێبینی",

      //schedule screen
      "sub-schedule": "خشتەی لاوەکی",
      "Saturday": "شەممە",
      "Sunday": "یەکشەممە",
      "Monday": "دووشەممە",
      "Tuesday": "سێشەممە",
      "Wednesday": "چوارشەممە",
      "Thursday": "پێنج شەممە",
      "Friday": "هەینی",
      "get-location": " شوێن لەسەر نەخشە",

      //EmptyStatus
      "cart-empty": "سەبەتەکە بەتاڵە",
      "notification-empty": "ئاگانامەکان بەتاڵە",
      "Favorite-empty": "دڵخوازەکان بەتاڵە",

      //Buttons
      "accept": "ڕازیبون",
      "reject": "ڕەتکردنەوە",
      "approve": "پەسەند کردن",
      "buy": "بکڕە",
      "submit": "ناردن",
      "upload-image": "بارکردنی وێنە",
      "reset": "دووبارە ڕێک بخەوە",
      "cancel": "هەڵوەشاندنەوه",
      "close": "داخستن",
      "call": "پەیوەندی",

      //other
      "new-filter": "نوێ",
      "accept-filter": "پەسەند کراو",
      "reject-filter": "ڕەتکراوە",
      "map": "نەخشە",
      "shop-list": "لیستی دووکان",
      "quantity": "چەندێتی",
      "no-name": "بێ ناو ",
      "list-favorite": " لیستی دڵخوازەکان ",
      "no-favorite": " هیچ دڵخوازەکان ",
      "no-notifications": " هیچ ئاگانامێک نییە",
      "order-item": "داواکردنی بەندەکان",
      "warning": "ئاگاداری",
      "last-version-already": "کاربەرنامەت نوێکرایەوە بۆ دوا وەشان.. ",
      "no-requests": "هیچ داواکارییەک نییە",
      "view": "نیشاندان",
      "light": "ڕوناک",
      "dark": "تاریک",
      "clear-all": "هەموو بسڕەوە",
      "notification-status": "لێرەدا ئاگانامەی نوێ هەر ئێستا ! بیپشکنە",
      "email": "ئیمەیل",
      "car-number": "ژمارەی ئۆتۆمبێل",
      "register-by": "تۆمارکراوە لەلایەن",
      "business-class": "پۆلی کار",
      "code": "کۆد",


      //time
      "year": "ساڵ",
      "years": "ساڵ",
      "month": "مانگ",
      "months": "مانگ",
      "week": "هەفتە",
      "weeks": "هەفتە",
      "day": "ڕۆژ",
      "days": "ڕۆژ",
      "hour": "کاتژمێر",
      "hours": "کاتژمێر",
      "minute": "خولەک",
      "minutes": "خولەک",
      "just-now": "هەر ئێستا",
      "ago": "پێش ئێستا",
    },
    'ar': {
//login
      'login': "تسجیل دخول",
      'logout': "الخروج",
      'sale-person': "مندوب مبعات",
      'shop': "متجر",
      'nawras': "نورس",
      'welcome': "أهلًا وسهلًا",
      'phone number': "رقم الهاتف",
      'password': "كلمه المرور",
      'forget something': "ننسى شيئا؟!",
      'sure-log-out': "هل أنت متأكد من أنك سوف الخروج؟",
      'log-out': " الخروج",
      "forget-password-warning":
          "هل لديك أي مشاكل أثناء تسجيل الدخول؟! n للحصول على وإعادة تعيين كلمة المرور فقط اتصل شركتنا... ",
      "password-short": "كلمة المرور قصيرة جداً..",
      "number-not-valid": "يجب أن يكون رقم الهاتف 7 أو أكثر..",

//home screen
      "home": "المنزل",
      "activity": "النشاط",
      "requests": "طلبات",
      "request": "طلب",
      "favorites": "المفضله",
      "offers": "يقدم",
      "categories": "فئات",
      "details-product": "تفاصيل المنتج",
      "search": "البحث",
      "search-hint": "البحث عن شيء",
      "all": "جميع",
      "most-popular": "الأكثر شعبية",
      "best-seller": "أفضل بائع",
      "new-product": " منتج جديد",
      "settings": "اعدادات",
      "profile": "التعريف",
      "view-profile": "عرض ملف التعريف",
      "feedback": "ردود الفعل",
      "language": "اللغة",
      "display-mode": " وضع العرض",
      "contact": " الاتصال",
      "contact-us": " الاتصال",
      "about": " ده رباره",
      "schedule": "الجدول  للعمل",
      "notifications": " الاخطارات",
      "cart": " عربه",
      "order-count": "عدد الطلبات",
      "change-language": "تغيير اللغة",
      "total-price": "السعر الإجمالي ",
      "total-products": "مجموع المنتجات",
      "search-for-product": "البحث عن المنتجات ...",
      "type-here": "اكتب هنا ...",
      "exit": "چوونەدەرەوە",
      "sure-exit": "هل أنت متأكد من إنهاء التطبيق؟",
      "select-market": "اختر سوق",
      "update": "تحديث",

// Cart order
      'the-order-was-successful': 'تم نجاح الطلب',
      "buying-these-products": "أنت متأكد من أنك تشتري هذه المنتجات.",

//details product screen
      "add-to-card": "إضافة إلى البطاقة",
      "product-already-order": "هذا المنتج بالفعل!",
      "add-to-your-a-cart": "أضف إلى سلة التسوق",
      "expire-date": "تاريخ انتهاء الصلاحية",
      "price": "السعر",
      "weight": "الوزن",
      "package-weight": "وزن الحزمة",

//Profile Screen
      "full-name": " الاسم الكامل",
      "number-phone": " رقم هاتف",
      "user-type": "نوع المستخدم",
      "location": "موقع",
      "zone": "المنطقه",
      "market": "السوق",
      "phone": "الهاتف",
      "area": "قسم",
      "date": "تاريخ",
      "items": "العناصر",
      "item": "العنصر",

//Feedback Screen
      "feedback-title": "أرسل إلينا ملاحظاتك",
      "feedback-desc":
          "هل لديك اقتراح أو العثور على بعض التصحيح؟ \n إعلامنا في الحقل أدناه.",
      "title": "عنوان",
      "name": "اسم",
      "valid-name": "اكتب اسم صالح الرجاء ...",
      "valid-title": "اكتب عنوان صالح الرجاء ...",
      "valid-message": "اكتب رسالة صالحة الرجاء ...",
      "title-desc": "كيف كما تجربتك",
      "desc-desc": "وصف تجربتك هنا",

//Marketing Screen
      "marketing-form": "نموذج التسويق",
      "fill-out-feedback": "املأ نموذج الملاحظات أدناه",
      "market-info": "معلومات السوق",
      "old-new": "قديم أو جديد",
      "do-have": "هل لديك منتج النورس",
      "if-do": "إذا لم تستخدم نورس المنتج، واسمحوا لنا أن نعرف لماذا؟",
      "barprsy-mushtaryat": "موظف العملاء",
      "barprs": "موظف",
      "expo": "تفسير",
      "bronze": "البرونزيه",
      "silver": "الفضه",
      "gold": "الذهب",
      "platinum": "البلاتين",
      "name-of-market": "اسم السوق:",
      "owner-name": "اسم المالك:",
      "address": "عنوان:",
      "near": "قرب:",
      "old": "القديمه",
      "new": "الجديد",
      "yes": "نعم",
      "no": "لا",
      "type": "نوع",
      "plural": "جمع",
      "singular": "المفرد",
      "volume": "حجم",
      "small": "الصغيره",
      "medium": "متوسط",
      "large": "كبيره",
      "mini-market": "سوق صغير",
      "super-market": "سوبر ماركت",
      "hyper-market": "السوق المفرط",
      "image": "الصوره",
      "note": "ملاحظه",
      "add-note": "إضافة ملاحظة",

//schedule screen
      "sub-schedule": "الجدول الفرعي",
      "Saturday": "السبت",
      "Sunday": "الأحد",
      "Monday": "الاثنين",
      "Tuesday": "الثلاثاء",
      "Wednesday": "الأربعاء",
      "Thursday": "الخميس",
      "Friday": "الجمعة",
      "get-location": " الموقع على الخريطة",

//EmptyStatus
      "cart-empty": "العربة فارغة",
      "notification-empty": "الإعلامات فارغة",
      "Favorite-empty": "المفضلة فارغة",

//Buttons
      "accept": "قبول",
      "reject": "رفض",
      "approve": "الموافقه",
      "buy": "شراء",
      "submit": "إرسال",
      "upload-image": "تحميل صورة",
      "reset": "اعاده تعيين",
      "cancel": "إلغاء",
      "close": "اغلاق",
      "call": "الاتصال",

//other
      "new-filter": "الجديد",
      "accept-filter": "قبلت",
      "reject-filter": "رفض",
      "map": "خريطه",
      "quantity": "كميه",
      "shop-list": "قائمة المتاجر",
      "no-name": "لا اسم ",
      "list-favorite": "قائمة المفضلة ",
      "no-favorite": "لا المفضلة ",
      "no-notifications": "لا يوجد أي إشعارات",
      "order-item": " عناصر الطلب",
      "warning": "تحذير",
      "last-version-already": "تم تحديث التطبيق الخاص بك إلى الإصدار الأخير.. ",
      "no-requests": "لا يوجد أي طلبات",
      "view": "عرض",
      "light": "ضوء",
      "dark": "الظلام",
      "clear-all": "مسح الكل",
      "notification-status": "هنا إشعار جديد الآن! التحقق من ذلك",
      "email": "البريد الإلكتروني",
      "car-number": "رقم السيارة",
      "register-by": "التسجيل من قبل",
      "business-class": "درجة رجال الأعمال",
      "code": "رمز",

//time
      "year": "سنة",
      "years": "سنوات",
      "month": "الشهر",
      "months": "أشهر",
      "week": "الاسبوع",
      "weeks": "اسابيع",
      "day": "اليوم",
      "days": "أيام",
      "hour": "ساعه",
      "hours": "ساعات",
      "minute": "دقيقه",
      "minutes": "دقائق",
      "just-now": "فقط الآن",
      "ago": "قبل",
    },
    'en': {
//login
      'login': "Login",
      'logout': "Log Out",
      'sale-person': "Sale Person",
      'shop': "Shop",
      'nawras': "Nawras",
      'welcome': "Welcome !",
      'phone number': "Phone Number",
      'password': "Password",
      'forget something': "Forget Something?!",
      'sure-log-out': "Are you sure you will Logout ?",
      'log-out': "Log Out",
      "forget-password-warning":
          "Do you Have any Issues During Logging in ?! \n To get and Reset Password just Contact Our Company...  ",
      "password-short": "Your Password is too short..",
      "number-not-valid": "Phone number Should be 7 or more..",

//home screen
      "home": "Home",
      "activity": "Activity",
      "requests": "Requests",
      "request": "Request",
      "favorites": "Favorites",
      "offers": "Offers",
      "categories": "Categories",
      "details-product": "Details Product",
      "search": "Search",
      "search-hint": "Search For Something",
      "all": "All",
      "most-popular": "Most Popular",
      "best-seller": "Best Seller",
      "new-product": " New Product",
      "settings": "Settings",
      "profile": "Profile ",
      "view-profile": "View Profile",
      "feedback": "Feedback",
      "language": "Language",
      "display-mode": " Display Mode",
      "contact": " Contact",
      "contact-us": " Contact Us",
      "about": "About",
      "schedule": "Schedule",
      "notifications": " Notifications",
      "cart": " Cart",
      "order-count": "Order Count",
      "change-language": "Change Language",
      "total-price": "Total Price ",
      "total-products": "Total Products",
      "search-for-product": "Search For Products ...",
      "type-here": "Type here ...",
      "exit": "Exit",
      "sure-exit": "Are you Sure Exit Application ?",
      "select-market": "Select a Market",
      "update": "Update",

// Cart order
      'the-order-was-successful': 'The order was successful',
      "buying-these-products": "you're sure you're buying these products",

//details product screen
      "add-to-card": "Add To Card",
      "product-already-order": "This product already order!",
      "add-to-your-a-cart": "Add to your a cart",
      "expire-date": "Expire Date",
      "price": "Price",
      "weight": "Weight",
      "package-weight": "Package Weight",

//Profile Screen
      "full-name": "Full Name",
      "number-phone": "Number Phone",
      "user-type": "User Type",
      "location": "Location",
      "zone": "Zone",
      "market": "Market",
      "phone": "Phone",
      "area": "Area",
      "date": "Date",
      "items": "Items",
      "item": "Item",

//Feedback Screen
      "feedback-title": "Send us Your Feedback",
      "feedback-desc":
          "Do you have a Suggestion or found some debug?\n Let us know in field below.",
      "title": "Title",
      "name": "Name",
      "valid-name": "Write Valid Name Please ...",
      "valid-title": "Write Valid Title Please ...",
      "valid-message": "Write Valid Message Please ...",
      "title-desc": "How as your experience",
      "desc-desc": "Describe your experience here",

//Marketing Screen
      "marketing-form": "Marketing Form",
      "fill-out-feedback": "Fill Out The Below Feedback Form",
      "market-info": "Market Info",
      "old-new": "Old Or New",
      "do-have": "Do you have Nawras Product",
      "if-do": "If They Do Not Use Nawras Product, Let Us Know Why?",
      "barprsy-mushtaryat": "Barprsy Mushtaryat",
      "barprs": "Barprs",
      "expo": "Explanation",
      "bronze": "Bronze",
      "silver": "Silver",
      "gold": "Gold",
      "platinum": "Platinum",
      "name-of-market": "Name Of Market:",
      "owner-name": "Owner Name:",
      "address": "Address:",
      "near": "Near:",
      "old": "Old",
      "new": "New",
      "yes": "Yes",
      "no": "No",
      "type": "Type",
      "plural": "Plural",
      "singular": "Singular",
      "volume": "Volume",
      "small": "Small",
      "medium": "Medium",
      "large": "Large",
      "mini-market": "Mini Market",
      "super-market": "Super Market",
      "hyper-market": "Hyper Market",
      "image": "Image",
      "note": "Note",
      "add-note": "Add Note",

//schedule screen
      "sub-schedule": "Sub Schedule",
      "Saturday": "Saturday",
      "Sunday": "Sunday",
      "Monday": "Monday",
      "Tuesday": "Tuesday",
      "Wednesday": "Wednesday",
      "Thursday": "Thursday",
      "Friday": "Friday",
      "get-location": "Location On Map",

//EmptyStatus
      "cart-empty": "Cart Is Empty",
      "notification-empty": "Notifications Is Empty",
      "Favorite-empty": "Favorite Is Empty",

//Buttons
      "accept": "Accept",
      "reject": "Reject",
      "approve": "Approve",
      "buy": "Buy",
      "submit": "Submit",
      "upload-image": "Upload Image",
      "reset": "Reset",
      "cancel": "Cancel",
      "close": "Close",
      "call": "Call",

//other
      "new-filter": "New",
      "accept-filter": "Accepted",
      "reject-filter": "Rejected",
      "map": "Map",
      "shop-list": "Shop List",
      "quantity": "Quantity",
      "no-name": "No Name",
      "list-favorite": "List Of Favorites",
      "no-favorite": " No Favorite ",
      "no-notifications": "No Notifications",
      "order-item": "Order Items",
      "warning": "Warning",
      "last-version-already": "Your App Updated to Last Version.. ",
      "no-requests": "No Requests",
      "view": "View",
      "light": "Light",
      "dark": "Dark",
      "clear-all": "Clear All",
      "notification-status": "Here a New Notification right now ! check it",
      "email": "Email",
      "car-number": "Car Number",
      "register-by": "Register By",
      "business-class": "Business Class",
      "code": "Code",


//time
      "year": "Year",
      "years": "Years",
      "month": "Month",
      "months": "Months",
      "week": "Week",
      "weeks": "Weeks",
      "day": "Day",
      "days": "Days",
      "hour": "Hour",
      "hours": "Hours",
      "minute": "Minute",
      "minutes": "Minutes",
      "just-now": "Just Now",
      "ago": "Ago",
    }
  };
}
